/* sol_wallet_core.h — auto-generated by cbindgen. DO NOT EDIT. */
#ifndef SOL_WALLET_CORE_H
#define SOL_WALLET_CORE_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/* Buffer-size constants — mobile consumer allocates via these. */
#define SOL_WALLET_MNEMONIC_BUF_LEN 256
#define SOL_WALLET_SECRET_LEN      32
#define SOL_WALLET_PUBKEY_LEN      44
#define SOL_WALLET_SIGNATURE_LEN   64
#define SOL_WALLET_HASH_LEN        32

#ifdef __cplusplus
extern "C" {
#endif


#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Default outbound request rate (requests per second) for the per-
 * `RpcClient` rate limiter.
 */
#define sol_wallet_DEFAULT_RATE_LIMIT_RPS 50

/**
 * Default burst allowance for the per-`RpcClient` rate limiter.
 */
#define sol_wallet_DEFAULT_RATE_LIMIT_BURST 100

/**
 * Argon2id spec cap on memory_kb (~4 GB). Envelopes claiming more
 * fail `Error::InvalidKdfParams` (L13 step 10 Sept 11 — bounded
 * Argon2id memory cap. Per L13 post-push security review:
 * 256 MiB is comfortably above DESKTOP (64 MiB) + MOBILE (16 MiB)
 * defaults but well below the 4 GiB attacker-DOS threshold.
 */
#define sol_wallet_KDF_MEMORY_KB_MAX (256 * 1024)

/**
 * Argon2id iteration cap. Prevents attacker-tuned envelopes that
 * maximize CPU pressure within the memory cap.
 */
#define sol_wallet_KDF_ITERATIONS_MAX 100

/**
 * Argon2id parallelism cap. Prevents thread-flooding within the
 * memory cap.
 */
#define sol_wallet_KDF_PARALLELISM_MAX 16

/**
 * Current envelope version. Bumped on AEAD / KDF changes.
 */
#define sol_wallet_ENVELOPE_VERSION 1

/**
 * Default max-attempts for `send_and_confirm`. V0.1 = 1 (no retry);
 * V0.1.5 = 3 with exponential backoff.
 */
#define sol_wallet_DEFAULT_SEND_MAX_ATTEMPTS 1

/**
 * Default compute unit limit per Phase 3.1 Step 4 + Q8.
 *
 * Matches Solana's validator default (200_000) divided to leave headroom
 * for a single SOL transfer (Phantom-equivalent wallets send this when
 * the user does not override; the wallet CLI exposes `--cu-limit` to
 * raise or lower it).
 */
#define sol_wallet_DEFAULT_COMPUTE_UNIT_LIMIT 150000

/**
 * Solana-native lamport amount.
 *
 * Holds `u64` lamports. Construct via [`Amount::from_lamports`] for
 * wire-level inputs or [`Amount::from_sol`] for user-facing decimal
 * inputs (the latter validates; the former is infallible).
 */
typedef struct sol_wallet_Amount sol_wallet_Amount;

/**
 * Argon2id parameters. Recorded in the JSON envelope and bound
 * into the AES-GCM AAD.
 */
typedef struct sol_wallet_KdfParams sol_wallet_KdfParams;







/**
 * Initialize the global `WalletManager` rooted at `data_dir`.
 *
 * Idempotent — second call returns `FfiError::Ok` without replacing
 * the existing manager (operator must explicitly reset to swap).
 */
int32_t sol_wallet_init(const char *data_dir, uintptr_t data_dir_len);

/**
 * `sol_wallet_create_mnemonic` — Step 2 stub.
 */
int32_t sol_wallet_create_mnemonic(char *out_id,
                                   uintptr_t out_id_len,
                                   char *out_mnemonic,
                                   uintptr_t out_mnemonic_len,
                                   const char *password,
                                   uintptr_t password_len,
                                   const char *cluster,
                                   uintptr_t cluster_len);

/**
 * `sol_wallet_import_mnemonic` — Step 3 stub.
 */
int32_t sol_wallet_import_mnemonic(char *out_id,
                                   uintptr_t out_id_len,
                                   const char *in_mnemonic,
                                   uintptr_t in_mnemonic_len,
                                   const char *password,
                                   uintptr_t password_len,
                                   const char *cluster,
                                   uintptr_t cluster_len);

/**
 * `sol_wallet_unlock` — Step 4 real impl (H3 + H4).
 */
int32_t sol_wallet_unlock(uint8_t *out_secret,
                          uintptr_t out_secret_len,
                          const char *id,
                          uintptr_t id_len,
                          const char *password,
                          uintptr_t password_len);

/**
 * `sol_wallet_lock` — Step 5 real impl (H3/M14 auto-zero).
 */
int32_t sol_wallet_lock(const char *id, uintptr_t id_len);

/**
 * `sol_wallet_get_address` — Step 6 real impl. Reads pubkey from
 * stored wallet record (no decrypt needed — pubkey is in plaintext
 * header).
 */
int32_t sol_wallet_get_address(char *out_pubkey,
                               uintptr_t out_pubkey_len,
                               const char *id,
                               uintptr_t id_len);

/**
 * `sol_wallet_sign_transaction` — Step 7 stub (real impl applies M9
 * domain-separation prefix).
 */
int32_t sol_wallet_sign_transaction(uint8_t *out_sig,
                                    uintptr_t out_sig_len,
                                    const uint8_t *in_message,
                                    uintptr_t in_message_len,
                                    const char *id,
                                    uintptr_t id_len);

/**
 * `sol_wallet_send_sol` — Step 8 stub (real impl enforces H5 policy gate).
 */
int32_t sol_wallet_send_sol(uint8_t *out_sig,
                            uintptr_t out_sig_len,
                            const char *id,
                            uintptr_t id_len,
                            const char *to,
                            uintptr_t to_len,
                            uint64_t amount_lamports,
                            uint64_t priority_fee);

/**
 * `sol_wallet_send_spl` — Step 9 stub (real impl enforces H5 policy gate).
 */
int32_t sol_wallet_send_spl(uint8_t *out_sig,
                            uintptr_t out_sig_len,
                            const char *id,
                            uintptr_t id_len,
                            const char *mint,
                            uintptr_t mint_len,
                            const char *to,
                            uintptr_t to_len,
                            uint64_t amount);

/**
 * `sol_wallet_get_balance_sol` — Step 10 stub.
 */
int32_t sol_wallet_get_balance_sol(uint64_t *out_lamports,
                                   const char *address,
                                   uintptr_t address_len);

/**
 * `sol_wallet_get_balance_spl` — Step 10 stub.
 */
int32_t sol_wallet_get_balance_spl(uint64_t *out_balance,
                                   uint8_t *out_decimals,
                                   const char *address,
                                   uintptr_t address_len,
                                   const char *mint,
                                   uintptr_t mint_len);

/**
 * `sol_wallet_last_error_message` — Step 11. **IMPLEMENTED.**
 *
 * Returns the most recent per-thread error message (scrubbed per M10).
 * Mobile consumer calls this after each non-zero FFI return.
 *
 * Returns the length written (excluding NUL) on success;
 * `FfiError::BufTooSmall` if the caller's buffer is too small
 * (then `last_error` itself describes the required size).
 */
int32_t sol_wallet_last_error_message(char *out_msg, uintptr_t buf_len);

/**
 * `sol_wallet_panic_message_clear` — Step 11. **IMPLEMENTED.**
 */
int32_t sol_wallet_panic_message_clear(void);

/**
 * `sol_wallet_zeroize` — H3 fix. **IMPLEMENTED.**
 *
 * Volatile-write zeros a caller-supplied buffer. Mobile consumer MUST
 * call this on every `out_secret` buffer returned by
 * `sol_wallet_unlock` once the secret has been copied into the
 * consumer's `Uint8List` / `Data` / `ByteArray` (or wherever the
 * mobile-side secret is held).
 */
int32_t sol_wallet_zeroize(uint8_t *buf, uintptr_t len);

/**
 * `sol_wallet_set_policy` — H5. STUB (audit recommendation: ship V0.1
 * with `unrestricted` default; real impl follows operator sign-off).
 */
int32_t sol_wallet_set_policy(const char *id,
                              uintptr_t id_len,
                              uint64_t max_per_tx_lamports,
                              uint64_t daily_limit_lamports,
                              const char *password,
                              uintptr_t password_len);

/**
 * `sol_wallet_get_policy` — H5 companion read.
 */
int32_t sol_wallet_get_policy(uint64_t *out_max_per_tx,
                              uint64_t *out_daily_limit,
                              const char *id,
                              uintptr_t id_len);

/**
 * `sol_wallet_default_cluster` — M16. Returns the cluster the wallet
 * manager is configured to use when caller omits cluster on create.
 */
int32_t sol_wallet_default_cluster(char *out_cluster, uintptr_t buf_len);

#ifdef __cplusplus
}
#endif

#endif /* SOL_WALLET_CORE_H */
