import 'dart:async';
import 'dart:developer' as developer;

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';

import '../../core/btc/btc_command.dart';
import '../../core/btc/btc_error.dart';
import '../../core/btc/models/wallet_created.dart';
import '../../core/btc/btc_error_messages.dart';
import '../../core/logging/btc_log_filter.dart';
import '../../core/secrets/password_supply.dart';
import '../../providers/btc_providers.dart';
import '../../providers/wallet_providers.dart';
import '../../routing/wallet_routes.dart';
import '../../widgets/password_field.dart';
import '../../widgets/status_badge.dart';
import 'mnemonic_display_dialog.dart';

/// Form for Story 1 + 20 — generate a fresh BIP-39 mnemonic with a
/// password + chosen word count + network + address type, then show
/// [MnemonicDisplayDialog] so the user can back it up.
///
/// **Secret handling** (L12 CRITICAL #2 + Task 5/6/7 chain):
/// - The password is routed through `withPasswordFile` (Task 6) which
///   produces a mode-0600 temp file; the password NEVER appears in
///   `argv` of the `btc` call.
/// - The mnemonic generated by `btc wallet create` arrives in the
///   `WalletCreated` DTO; we hold it ONLY inside
///   [MnemonicDisplayDialog] for the duration of the dialog and let
///   it go when the user dismisses. We do NOT log it, do NOT log the
///   `BtcCommand.argv`, and force-clear `_password` (the screen's
///   own copy) before showing the dialog. The `PasswordField`'s
///   internal `TextEditingController` is cleared in its own
///   `dispose()` (Task 15) which fires after navigation; clearing
///   that earlier would require a `PasswordField.clear()` seam
///   flagged for v0.2.
/// - `BtcLogFilter` is wired into `dart:developer.log` (per Task 17
///   post-PR fixup) so any non-BtcError exception reaching the catch
///   path is redacted before landing in DevTools / VM-service.
///
/// **Error funnel** mirrors Task 17: [BtcError] → kind-mapped message
/// via [userMessageForBtcError]; anything else is rendered via the
/// redacted `toString()`. Raw stderr NEVER surfaces in the UI.
///
/// **Post-success**: the wallet-list autoDispose family is refreshed
/// via `notifier.refresh()` (Task 13 L31 lesson — `ref.invalidate` is
/// the same effect but `notifier.refresh()` reads cleanly off the
/// provider handle).
class WalletCreateScreen extends ConsumerStatefulWidget {
  const WalletCreateScreen({super.key, required this.network});
  final String network;

  @override
  ConsumerState<WalletCreateScreen> createState() => _WalletCreateScreenState();
}

class _WalletCreateScreenState extends ConsumerState<WalletCreateScreen> {
  int _words = 12;
  String _addressType = 'native-segwit';
  String _password = '';
  bool _running = false;
  BtcError? _error;

  Future<void> _submit() async {
    if (_password.isEmpty) return;
    setState(() {
      _running = true;
      _error = null;
    });
    try {
      final invoker = await ref.read(btcInvokerProvider.future);
      // `withPasswordFile` is typed `Future<void>` (Task 5/6 thin
      // delegate); capture the parsed DTO via a closure variable.
      // The Task 6.1 follow-up (per type-design post-PR feedback)
      // is to re-parameterise both `withTempSecretFile<T>` and
      // `withPasswordFile<T>` to return `T`, which collapses this
      // capture dance into a single `await` expression.
      WalletCreated? result;
      await withPasswordFile(_password, (path) async {
        final r = await invoker.invoke<WalletCreated>(
          BtcCommand.walletCreate(
            words: _words,
            network: widget.network,
            addressType: _addressType,
            passwordFilePath: path,
          ),
          parse: (j) => WalletCreated.fromJson(j as Map<String, dynamic>),
        );
        result = r;
      });
      final r = result;
      if (r == null || !mounted) return;
      // Force-clear our password field state before showing mnemonic.
      // (`PasswordField`'s controller is cleared in its own dispose;
      // see v0.2 backlog for an explicit `clear()` seam.)
      setState(() {
        _password = '';
      });
      await showDialog<void>(
        context: context,
        barrierDismissible: false,
        builder: (_) => MnemonicDisplayDialog(
          mnemonic: r.mnemonic,
          walletId: r.id,
          firstAddress: r.firstAddress,
        ),
      );
      if (!mounted) return;
      // Navigate back to the wallet list immediately. The
      // walletsListProvider autoDispose family re-fetches when its
      // next listener subscribes — but the user is already on the
      // WalletListScreen route so we kick off an explicit refresh.
      // Fire-and-forget via `unawaited` so navigation isn't blocked
      // by the re-fetch (defence against UI lockups while btc CLI
      // runs `wallet list`).
      context.go(WalletRoutes.wallets(widget.network));
      unawaited(
        ref.read(walletsListProvider(widget.network).notifier).refresh(),
      );
    } on BtcError catch (e) {
      if (mounted) setState(() => _error = e);
    } catch (e, st) {
      // Defence-in-depth: dart:developer.log bypasses package:logging,
      // so pipe the redacted form through ourselves (Task 17 lesson).
      // v0.2 follow-up: pass opaque `denyTokens: [_password]` so the
      // bare password token is scrubbed even if the redactor's
      // BIP-39-word shape misses it.
      const filter = BtcLogFilter();
      developer.log(
        'wallet_create failed',
        name: 'WalletCreateScreen',
        error: filter.redact(e.toString()),
        stackTrace: st,
      );
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Could not create wallet.')),
        );
      }
    } finally {
      if (mounted) setState(() => _running = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final error = _error;
    return Scaffold(
      appBar: AppBar(title: Text('Create wallet (${widget.network})')),
      body: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            DropdownButtonFormField<int>(
              initialValue: _words,
              decoration: const InputDecoration(labelText: 'Words'),
              items: const [
                DropdownMenuItem(value: 12, child: Text('12')),
                DropdownMenuItem(value: 24, child: Text('24')),
              ],
              onChanged: (v) => setState(() => _words = v ?? 12),
            ),
            const SizedBox(height: 16),
            DropdownButtonFormField<String>(
              initialValue: _addressType,
              decoration: const InputDecoration(labelText: 'Address type'),
              items: const [
                DropdownMenuItem(value: 'legacy', child: Text('legacy')),
                DropdownMenuItem(
                    value: 'nested-segwit', child: Text('nested-segwit')),
                DropdownMenuItem(
                    value: 'native-segwit', child: Text('native-segwit')),
                DropdownMenuItem(value: 'taproot', child: Text('taproot')),
              ],
              onChanged: (v) =>
                  setState(() => _addressType = v ?? 'native-segwit'),
            ),
            const SizedBox(height: 16),
            PasswordField(onChanged: (v) => _password = v),
            const SizedBox(height: 16),
            if (error != null) ...[
              StatusBadge(kind: error.kind),
              const SizedBox(height: 8),
              Text(userMessageForBtcError(error)),
              const SizedBox(height: 8),
            ],
            FilledButton(
              key: const Key('wallet_create_submit'),
              onPressed: _running ? null : _submit,
              child: _running
                  ? const Text('Creating…')
                  : const Text('Create'),
            ),
          ],
        ),
      ),
    );
  }
}
