//! ERC-20 surface (Q3 — transfer calldata + Anvil-fork deploy/transfer/balanceOf).

use alloy_primitives::U256;
use alloy_sol_types::sol;

// Selectors for `transfer(address,uint256)` + `balanceOf(address)` are
// generated by the `sol!` macro below at compile time via
// `MockUSDC::transferCall::SELECTOR` + `MockUSDC::balanceOfCall::SELECTOR`.
// L12 finding: the previously hand-coded constants here would drift if
// the ABI signature ever changed. Removed; callers use the macro-generated
// constants.

sol! {
    contract MockUSDC {
        constructor(uint256 initialSupply) {
            _balances[msg.sender] = initialSupply;
        }

        mapping(address => uint256) public _balances;

        function balanceOf(address account) external view returns (uint256) {
            return _balances[account];
        }

        function transfer(address to, uint256 value) external returns (bool) {
            require(_balances[msg.sender] >= value, "insufficient");
            _balances[msg.sender] -= value;
            _balances[to] += value;
            return true;
        }
    }
}

/// USDC decimal precision (6). Pinned for V9 + use_case.
pub const USDC_DECIMALS: u8 = 6;

/// Build the U256 raw value for `n` USDC at 6 decimals.
pub fn usdc_to_raw(units: u64) -> U256 {
    U256::from(units) * U256::from(10_u64).pow(U256::from(USDC_DECIMALS as u64))
}
