//! Wallet ID — UUID v4 newtype for wallet-store filenames.
//!
//! Per ADR 0001 (`docs/superpowers/adrs/2026-08-11-adr-0001-btc-wallet-store.md`),
//! wallet files live at `$XDG_DATA_HOME/btc/wallets/<network>/<wallet_id>.enc`.
//! `<wallet_id>` is a UUID v4 (random, no PII) generated by [`WalletId::new`].
//!
//! **Type-system defense-in-depth** (parallel to `MnemonicCipherBlob` in #28
//! and `Aad<'a>` in #66): `WalletId(Uuid)` prevents callers from passing a
//! `String` (or an arbitrary `Uuid`) where a `WalletId` is expected. All
//! construction paths route through the single `validate()` gate — no
//! `From<Uuid>` constructor, manual `Serialize`/`Deserialize` impls
//! route through `TryFrom<Uuid>` so the gate can't be bypassed.

use std::fmt;
use std::str::FromStr;

use serde::{Deserialize, Serialize};
use uuid::{Uuid, Variant};

use crate::error::Error;

/// Wallet ID — UUID v4 newtype.
#[derive(Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct WalletId(Uuid);

/// Serialize via [`Uuid`]. Pair with [`Deserialize`] below.
impl Serialize for WalletId {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        self.0.serialize(s)
    }
}

/// Deserialize via [`Uuid`], routed through `TryFrom<Uuid>` → `validate()`.
/// Prevents bypass via derived transparent `Deserialize` (which would
/// accept arbitrary UUIDs, including nil / non-v4 / non-RFC-4122-variant).
impl<'de> Deserialize<'de> for WalletId {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        Uuid::deserialize(d)?
            .try_into()
            .map_err(|e: Error| serde::de::Error::custom(e.to_string()))
    }
}

impl WalletId {
    /// Generate a new random wallet ID (UUID v4).
    ///
    /// Routes through `validate()` so drift in `Uuid::new_v4`'s behavior
    /// is caught at construction, not parse.
    ///
    /// **Note**: `Default::default()` mints a fresh random v4 — same as
    /// `Self::new()`. This is intentional despite the struct-update
    /// footgun (`..Default::default()` silently replaces an existing
    /// `WalletId` with a new random one): the only legitimate use is
    /// `#[derive(Default)]` on config structs that need a placeholder.
    /// Direct calls to `WalletId::default()` should be replaced with
    /// explicit `WalletId::new()` calls so the intent is greppable.
    pub fn new() -> Self {
        let uuid = Uuid::new_v4();
        validate(uuid).expect("Uuid::new_v4() must produce a valid WalletId (RFC 4122 v4)")
    }
}

impl Default for WalletId {
    fn default() -> Self {
        Self::new()
    }
}

impl fmt::Display for WalletId {
    /// Standard hyphenated lowercase UUID form (RFC 4122 §3).
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0.hyphenated())
    }
}

impl fmt::Debug for WalletId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        // WalletId is not secret — unlike `Secret<T>`, Debug prints the
        // value. (See keys/secret.rs for the redaction pattern.)
        write!(f, "WalletId({})", self.0.hyphenated())
    }
}

impl FromStr for WalletId {
    type Err = Error;

    /// Parse a UUID string. Rejects empty/malformed input, nil, non-v4,
    /// and non-RFC-4122-variant. Accepts uppercase, hex-only, URN, and
    /// braced forms (all normalize via `Uuid::parse_str`); `Display`
    /// always emits canonical lowercase-hyphenated.
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let uuid = Uuid::parse_str(s)
            .map_err(|_| Error::WalletStore("invalid wallet id format".into()))?;
        validate(uuid)
    }
}

impl TryFrom<Uuid> for WalletId {
    type Error = Error;
    fn try_from(uuid: Uuid) -> Result<Self, Self::Error> {
        validate(uuid)
    }
}

/// Single validation gate. All construction paths (new, from_str,
/// TryFrom, Deserialize) route through here.
fn validate(uuid: Uuid) -> Result<WalletId, Error> {
    if uuid.get_variant() != Variant::RFC4122 {
        return Err(Error::WalletStore("invalid wallet id".into()));
    }
    if uuid.is_nil() {
        return Err(Error::WalletStore("invalid wallet id".into()));
    }
    match uuid.get_version() {
        Some(uuid::Version::Random) => Ok(WalletId(uuid)),
        Some(other) => Err(Error::WalletStore(format!(
            "invalid wallet id (unsupported version: v{})",
            other as u8
        ))),
        None => Err(Error::WalletStore("invalid wallet id".into())),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn new_actually_produces_v4_uuid() {
        // Verify version + variant (length-only check would accept any UUID version).
        for _ in 0..100 {
            let id = WalletId::new();
            assert_eq!(id.0.get_version(), Some(uuid::Version::Random));
            assert_eq!(id.0.get_variant(), uuid::Variant::RFC4122);
        }
    }

    #[test]
    fn two_new_ids_are_distinct() {
        // Probabilistic — collision odds for v4 are ~2^-122.
        let a = WalletId::new();
        let b = WalletId::new();
        assert_ne!(a, b);
    }

    #[test]
    fn display_roundtrips_through_from_str() {
        let id = WalletId::new();
        let s = id.to_string();
        let parsed: WalletId = s.parse().expect("display output must parse");
        assert_eq!(id, parsed);
    }

    #[test]
    fn display_is_lowercase_hyphenated() {
        let id = WalletId::new();
        let s = id.to_string();
        assert_eq!(s.len(), 36, "hyphenated UUID is 36 chars");
        assert_eq!(s.chars().filter(|c| *c == '-').count(), 4);
        assert!(s.chars().all(|c| c.is_ascii_hexdigit() || c == '-'));
    }

    #[test]
    fn from_str_accepts_v4_uuid() {
        let s = "550e8400-e29b-41d4-a716-446655440000";
        let id: WalletId = s.parse().expect("v4 must parse");
        assert_eq!(id.to_string(), s);
    }

    #[test]
    fn from_str_rejects_nil_uuid() {
        let s = "00000000-0000-0000-0000-000000000000";
        let err = WalletId::from_str(s).expect_err("nil must reject");
        assert!(matches!(err, Error::WalletStore(_)));
        assert_eq!(err.to_string(), "wallet store: invalid wallet id");
    }

    #[test]
    fn from_str_rejects_v1_uuid() {
        let s = "6ba7b810-9dad-11d1-80b4-00c04fd430c8";
        let err = WalletId::from_str(s).expect_err("v1 must reject");
        assert!(matches!(err, Error::WalletStore(_)));
        assert!(err.to_string().contains("unsupported version: v1"));
    }

    #[test]
    fn from_str_rejects_non_rfc4122_variant() {
        // Byte 8 = 0x40 → variant NCS, high nibble 4 → version 4.
        // This used to be accepted (only version nibble checked).
        let s = "550e8400-e29b-41d4-4070-406551440000";
        let err = WalletId::from_str(s).expect_err("non-RFC4122 variant must reject");
        assert!(matches!(err, Error::WalletStore(_)));
        assert_eq!(err.to_string(), "wallet store: invalid wallet id");
    }

    #[test]
    fn from_str_rejects_garbage() {
        let err = WalletId::from_str("not-a-uuid").expect_err("garbage rejects");
        assert!(matches!(err, Error::WalletStore(_)));
        assert_eq!(err.to_string(), "wallet store: invalid wallet id format");
    }

    #[test]
    fn from_str_rejects_empty() {
        let err = WalletId::from_str("").expect_err("empty rejects");
        assert!(matches!(err, Error::WalletStore(_)));
    }

    #[test]
    fn debug_shows_value_not_redacted() {
        let id = WalletId::new();
        let s = format!("{id:?}");
        assert!(s.starts_with("WalletId("));
    }

    #[test]
    fn copy_semantics_for_uuid_v4() {
        fn assert_copy<T: Copy>() {}
        assert_copy::<WalletId>();
        let a = WalletId::new();
        let b = a;
        let _ = a;
        assert_eq!(a, b);
    }

    #[test]
    fn try_from_uuid_rejects_v1() {
        let uuid = Uuid::parse_str("6ba7b810-9dad-11d1-80b4-00c04fd430c8").unwrap();
        let err = WalletId::try_from(uuid).expect_err("v1 must reject");
        assert!(matches!(err, Error::WalletStore(_)));
    }

    #[test]
    fn try_from_uuid_accepts_v4() {
        let uuid = Uuid::parse_str("550e8400-e29b-41d4-a716-446655440000").unwrap();
        let id = WalletId::try_from(uuid).expect("v4 must accept");
        assert_eq!(id.to_string(), "550e8400-e29b-41d4-a716-446655440000");
    }

    #[test]
    fn ord_implemented_for_sorting() {
        let mut ids = [WalletId::new(), WalletId::new(), WalletId::new()];
        ids.sort();
    }
}
